apiVersion: apps/v1
kind: Deployment
metadata:
  name: 	
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
        - name: helloworld
          image: DOCKER_IMAGE
          ports:
            - containerPort: 9000

---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9000
  type: LoadBalancer
