name: Docker Build And Push
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  HelloWorldService-Build:
 
    name: Build Docker Image
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout
          uses: actions/checkout@v2

        - name: Set up JDK 11
          uses: actions/setup-java@v4
          with:
            java-version: '11'
            distribution: 'temurin'
            cache: 'maven'
            cache-dependency-path: 'pom.xml' # optional
            server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
            settings-path: ${{ github.workspace }} # location for the settings.xml file

        - name: Build with Maven
          run: mvn -B package --file pom.xml

        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}

        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{secrets.AWS_ECR_REPO}}
            IMAGE_TAG: ${{ github.sha }}
          run: |
            docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

        - name: Update kube config
          run: aws eks update-kubeconfig --name ${{secrets.EKS_CLUSTER_NAME}} --region $AWS_REGION

        - name: Deploy to EKS
          run: |
            sed "s|DOCKER_IMAGE|$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s.yaml > test123.yaml
            echo `cat test123.yaml | grep "image"`
            echo "Reached...11$IMAGE_TAG"
            echo "Reached...22{$IMAGE_TAG}"
            echo "Reached...33${{IMAGE_TAG}}"
            kubectl apply -f test123.yaml
